### ISSUE TITLE
Neko’s Enchanted Books (nebs) has failed to load correctly

### ISSUE THREAD

**Issue by MatteoGisondi** [VazkiiMods/crucial2#183]
### Bug Description
Neko’s Enchanted Books (nebs) has failed to load correctly

## Platform
Linux Mint 19 Tara x86_64

## Logs
```---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 12/08/21 6:29 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.2.2.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.2.2.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.2.2.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.2.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.5-36.2.2.jar:36.2] {}
-- MOD nebs --
Details:
	Mod File: NekosEnchantedBooks-1.16-1.3.0.jar
	Failure message: Neko’s Enchanted Books (nebs) has failed to load correctly
		java.lang.RuntimeException: Attempted to load class net/minecraft/client/world/ClientWorld for invalid dist DEDICATED_SERVER
	Mod Version: 1.3.0
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/world/ClientWorld for invalid dist DEDICATED_SERVER
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.5-36.2.2.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_292] {}
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_292] {}
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_292] {}
	at java.lang.Class.getDeclaredMethod(Class.java:2128) ~[?:1.8.0_292] {}
	at net.minecraftforge.eventbus.EventBus.getDeclMethod(EventBus.java:83) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$null$4(EventBus.java:95) ~[eventbus-4.0.0.jar:?] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_292] {}
	at java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1577) ~[?:1.8.0_292] {}
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_292] {}
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) ~[?:1.8.0_292] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) ~[?:1.8.0_292] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_292] {}
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_292] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_292] {}
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531) ~[?:1.8.0_292] {}
	at net.minecraftforge.eventbus.EventBus.lambda$registerObject$7(EventBus.java:97) ~[eventbus-4.0.0.jar:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:1.8.0_292] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_292] {}
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_292] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_292] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_292] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_292] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_292] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_292] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_292] {}
	at net.minecraftforge.eventbus.EventBus.registerObject(EventBus.java:94) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:120) ~[eventbus-4.0.0.jar:?] {}
	at com.cgessinger.nebs.NekosEnchantedBooks.<init>(NekosEnchantedBooks.java:40) ~[nebs:1.3.0] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_292] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_292] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_292] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_292] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_292] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_292] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_292] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_292] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_292] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_292] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_292] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 4.15.0-140-generic
	Java Version: 1.8.0_292, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 1417551552 bytes (1351 MB) / 2107113472 bytes (2009 MB) up to 2107113472 bytes (2009 MB)
	CPUs: 4
	JVM Flags: 2 total; -Xms2G -Xmx2G
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.2.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.2.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.2.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.2.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.2.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.2
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		CyclopsCore-1.16.5-1.11.8.jar                     |Cyclops Core                  |cyclopscore                   |1.11.8              |CREATE_REG|Manifest: NOSIGNATURE
		BetterDungeons-1.16.4-1.2.jar                     |YUNG's Better Dungeons        |betterdungeons                |1.16.4-1.2          |CREATE_REG|Manifest: NOSIGNATURE
		secondchanceforge-1.2.0.jar                       |Second Chance Forge           |secondchanceforge             |1.2.0               |CREATE_REG|Manifest: NOSIGNATURE
		infernal-expansion-2.2.0.jar                      |Infernal Expansion            |infernalexp                   |2.2.0               |CREATE_REG|Manifest: NOSIGNATURE
		fish_in_planks-1.16.5-0.4.jar                     |Fish in Planks                |fish_in_planks                |1.16.5-0.4          |CREATE_REG|Manifest: NOSIGNATURE
		Architects-Palette-1.16.4-1.1.4.jar               |Architect's Palette           |architects_palette            |1.1.2               |CREATE_REG|Manifest: NOSIGNATURE
		glazedsymmetry-1.0.jar                            |Glazed Symmetry               |glazedsymmetry                |1.0                 |CREATE_REG|Manifest: NOSIGNATURE
		windowlogging-mc1.16.3_v0.0.4.jar                 |Windowlogging                 |windowlogging                 |0.0.4               |CREATE_REG|Manifest: NOSIGNATURE
		farsight-1.3.1-1.16.5.jar                         |Farsight                      |farsight_spyglasses           |1.3.1-1.16.5        |CREATE_REG|Manifest: NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.2.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.2        |CREATE_REG|Manifest: NOSIGNATURE
		Controlling-7.0.0.23.jar                          |Controlling                   |controlling                   |7.0.0.23            |CREATE_REG|Manifest: NOSIGNATURE
		Placebo-1.16.4-4.5.0.jar                          |Placebo                       |placebo                       |4.5.0               |CREATE_REG|Manifest: NOSIGNATURE
		citadel-1.7.3-1.16.5.jar                          |Citadel                       |citadel                       |1.7.3               |CREATE_REG|Manifest: NOSIGNATURE
		alexsmobs-1.11.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.11.1              |CREATE_REG|Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-12.jar                      |YUNG's API                    |yungsapi                      |1.16.4-Forge-12     |CREATE_REG|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.16.5-10.2.27.jar                |Bookshelf                     |bookshelf                     |10.2.27             |CREATE_REG|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		itemzoom-1.16.x-2.2.1.jar                         |Item Zoom Rekindled           |itemzoom                      |2.2.1               |CREATE_REG|Manifest: NOSIGNATURE
		forgery-1.16-1.3.5-rc2.jar                        |Forgery                       |fabrication                   |1.3.5-rc2           |CREATE_REG|Manifest: NOSIGNATURE
		SnowRealMagic-1.16.4-2.5.7.jar                    |Snow! Real Magic!             |snowrealmagic                 |2.5.7               |CREATE_REG|Manifest: NOSIGNATURE
		Paraglider-1.16.5-1.3.2.1.jar                     |Paraglider                    |paraglider                    |1.3.2.1             |CREATE_REG|Manifest: NOSIGNATURE
		supplementaries-1.16.5-0.15.2.jar                 |Supplementaries               |supplementaries               |1.16.5-0.15.0       |CREATE_REG|Manifest: NOSIGNATURE
		structure_gel-1.16.5-1.7.7.jar                    |Structure Gel API             |structure_gel                 |1.7.7               |CREATE_REG|Manifest: NOSIGNATURE
		PackMenu-1.16.4-2.4.2.jar                         |Pack Menu                     |packmenu                      |2.4.2               |CREATE_REG|Manifest: NOSIGNATURE
		chocolate-1.3.0-1.16.4.jar                        |Chocolate                     |chocolate                     |1.3.0-1.16.4        |CREATE_REG|Manifest: NOSIGNATURE
		FarmersDelight-1.16.5-0.4.6.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.4.6        |CREATE_REG|Manifest: NOSIGNATURE
		customizableelytra-1.16.4-1.5.4.jar               |Customizable Elytra           |customizableelytra            |1.16.4-1.5.4        |CREATE_REG|Manifest: NOSIGNATURE
		dungeons_plus-1.16.5-1.1.5.jar                    |Dungeons Plus                 |dungeons_plus                 |1.1.5               |CREATE_REG|Manifest: NOSIGNATURE
		skinned_lanterns-1.16.5-1.3.1.jar                 |Skinned Lanterns              |skinnedlanterns               |1.16.5-1.3.1        |CREATE_REG|Manifest: NOSIGNATURE
		shulker_enchantments-1.1.1.jar                    |Shulker Enchantments          |shulker_enchantments          |1.1.1               |CREATE_REG|Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.1.jar                         |Patchouli                     |patchouli                     |1.16.4-53.1         |CREATE_REG|Manifest: NOSIGNATURE
		leap-1.16.4-1.1.1.jar                             |Leap                          |leap                          |1.1.1               |CREATE_REG|Manifest: NOSIGNATURE
		YungsExtras-Forge-1.16.4-1.0.jar                  |YUNG's Extras                 |yungsextras                   |Forge-1.16.4-1.0    |CREATE_REG|Manifest: NOSIGNATURE
		BetterStrongholds-1.16.4-1.2.1.jar                |YUNG's Better Strongholds     |betterstrongholds             |1.16.4-1.2.1        |CREATE_REG|Manifest: NOSIGNATURE
		antiquewaystones-1.3.jar                          |Antique Waystones             |antiquewaystones              |1.3                 |CREATE_REG|Manifest: NOSIGNATURE
		sapience-1.16.5-1.1.2.jar                         |Sapience                      |sapience                      |1.1.2               |CREATE_REG|Manifest: NOSIGNATURE
		architectury-1.20.29-forge.jar                    |Architectury                  |architectury                  |1.20.29             |CREATE_REG|Manifest: NOSIGNATURE
		Chimes-1.16.5-0.9.5.jar                           |Chimes                        |chimes                        |0.9.5               |CREATE_REG|Manifest: NOSIGNATURE
		cloth-config-4.11.26-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.11.26             |CREATE_REG|Manifest: NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.4.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.4        |CREATE_REG|Manifest: NOSIGNATURE
		SimpleDiscordRichPresence-1.16.4-1.3.5.jar        |Simple Discord Rich Presence  |sdrp                          |1.16.4-1.3.5        |CREATE_REG|Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.43.jar                  |GeckoLib                      |geckolib3                     |3.0.43              |CREATE_REG|Manifest: NOSIGNATURE
		NekosEnchantedBooks-1.16-1.3.0.jar                |Neko’s Enchanted Books        |nebs                          |1.3.0               |ERROR     |Manifest: NOSIGNATURE
		BetterAdvancements-1.16.5-0.1.0.108.jar           |Better Advancements           |betteradvancements            |0.1.0.108           |CREATE_REG|Manifest: NOSIGNATURE
		StructuredCrafting-1.16.4-0.2.2.jar               |StructuredCrafting            |structuredcrafting            |0.2.2               |CREATE_REG|Manifest: NOSIGNATURE
		SaveMyStronghold-1.16.4-1.0.jar                   |Save My Stronghold!           |savemystronghold              |1.16.4-1.0          |CREATE_REG|Manifest: NOSIGNATURE
		QuarkOddities-1.16.3.jar                          |Quark Oddities                |quarkoddities                 |1.16.3              |CREATE_REG|Manifest: NOSIGNATURE
		Kiwi-1.16.5-3.5.2.jar                             |Kiwi                          |kiwi                          |3.5.2               |CREATE_REG|Manifest: NOSIGNATURE
		Notes-1.16.5-1.2.3.jar                            |Notes                         |notes                         |1.16.5-1.2.3        |CREATE_REG|Manifest: NOSIGNATURE
		ftb-library-forge-1605.3.1-build.58.jar           |FTB Library                   |ftblibrary                    |1605.3.1-build.58   |CREATE_REG|Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.118.jar                          |Just Enough Items             |jei                           |7.7.1.118           |CREATE_REG|Manifest: NOSIGNATURE
		the-conjurer-1.16.4-1.0.13.jar                    |The Conjurer                  |conjurer_illager              |1.0.13              |CREATE_REG|Manifest: NOSIGNATURE
		abnormals_core-1.16.5-3.2.0.jar                   |Abnormals Core                |abnormals_core                |3.2.0               |CREATE_REG|Manifest: NOSIGNATURE
		Fruitful-1.16.5-2.1.0.jar                         |Fruitful                      |fruitful                      |1.16.5-2.1.0        |CREATE_REG|Manifest: NOSIGNATURE
		environmental-1.16.5-1.1.0.jar                    |Environmental                 |environmental                 |1.1.0               |CREATE_REG|Manifest: NOSIGNATURE
		bamboo_blocks-1.16.5-3.0.0.jar                    |Bamboo Blocks                 |bamboo_blocks                 |3.0.0               |CREATE_REG|Manifest: NOSIGNATURE
		allurement-1.16.5-1.2.0.jar                       |Allurement                    |allurement                    |1.2.0               |CREATE_REG|Manifest: NOSIGNATURE
		peculiars-1.16.5-2.0.0.jar                        |Peculiars                     |peculiars                     |1.16.5-2.0.0        |CREATE_REG|Manifest: NOSIGNATURE
		buzzier_bees-1.16.5-3.0.1.jar                     |Buzzier Bees                  |buzzier_bees                  |3.0.1               |CREATE_REG|Manifest: NOSIGNATURE
		berry_good-1.16.5-4.1.1.jar                       |Berry Good                    |berry_good                    |4.1.1               |CREATE_REG|Manifest: NOSIGNATURE
		Enhanced-Mushrooms-1.16.5-3.0.9.jar               |Enhanced Mushrooms            |enhanced_mushrooms            |1.16.5-3.0.9        |CREATE_REG|Manifest: NOSIGNATURE
		Bayou-Blues-1.16.5-1.0.5.jar                      |Bayou Blues                   |bayou_blues                   |1.16.5-1.0.5        |CREATE_REG|Manifest: NOSIGNATURE
		differentiate-1.16.5-0.5.3.jar                    |Differentiate                 |differentiate                 |0.5.3               |CREATE_REG|Manifest: NOSIGNATURE
		cookielicious-1.16.5-1.4.1.jar                    |Cookielicious                 |cookielicious                 |1.4.1               |CREATE_REG|Manifest: NOSIGNATURE
		seals-1.16.3-2.1.2.jar                            |Seals                         |seals                         |2.1.2               |CREATE_REG|Manifest: NOSIGNATURE
		Better-Badlands-1.16.5-2.0.3.jar                  |Better Badlands               |better_badlands               |1.16.5-2.0.3        |CREATE_REG|Manifest: NOSIGNATURE
		extraboats-1.16.5-2.1.0.jar                       |Extra Boats                   |extraboats                    |2.1.0               |CREATE_REG|Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.2.jar                        |Waystones                     |waystones                     |7.6.2               |CREATE_REG|Manifest: NOSIGNATURE
		shutupexperimentalsettings-1.0.3.jar              |Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.3               |CREATE_REG|Manifest: NOSIGNATURE
		irregularchef-1.16.5-1.0.1.jar                    |The Irregular Chef            |irregularchef                 |1.16.5-1.0.1        |CREATE_REG|Manifest: NOSIGNATURE
		fantasy-forge-1.1.1.jar                           |Fantasy Mounts                |fantasy                       |1.0                 |CREATE_REG|Manifest: NOSIGNATURE
		bedspreads-forge-1.16.5-5.1.0.2.jar               |Bedspreads                    |bedspreads                    |1.16.5-5.1.0.2      |CREATE_REG|Manifest: NOSIGNATURE
		blockswap-1.1.1.jar                               |Block Swap                    |blockswap                     |1.1.1               |CREATE_REG|Manifest: NOSIGNATURE
		Toast-Control-1.16.4-4.3.1.jar                    |Toast Control                 |toastcontrol                  |4.3.1               |CREATE_REG|Manifest: NOSIGNATURE
		JEITweaker-1.16.5-1.0.1.34.jar                    |JEI Tweaker                   |jeitweaker                    |1.0.1.34            |CREATE_REG|Manifest: NOSIGNATURE
		sodium-forge-2.9.10+rev.ea6353c.jar               |SodiumReforged                |sodium                        |2.9.10+rev.ea6353c  |CREATE_REG|Manifest: NOSIGNATURE
		CraftTweaker-1.16.5-7.1.0.378.jar                 |CraftTweaker                  |crafttweaker                  |7.1.0.378           |CREATE_REG|Manifest: NOSIGNATURE
		frozenup-1.0.1.jar                                |Frozen Up                     |frozenup                      |1.0.1               |CREATE_REG|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.2-universal.jar                 |Forge                         |forge                         |36.2.2              |CREATE_REG|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		seasonals-1.16.5-2.0.0.jar                        |Seasonals                     |seasonals                     |1.16.5-2.0.0        |CREATE_REG|Manifest: NOSIGNATURE
		neapolitan-1.16.5-2.1.0.jar                       |Neapolitan                    |neapolitan                    |2.1.0               |CREATE_REG|Manifest: NOSIGNATURE
		DynamicSurroundings-1.16.4-4.0.4.2.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.4.2      |CREATE_REG|Manifest: b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		selene-1.16.5-1.6.jar                             |Selene                        |selene                        |1.16.5-1.0          |CREATE_REG|Manifest: NOSIGNATURE
		antiqueatlas-6.0.1-forge-mc1.16.5.jar             |Antique Atlas                 |antiqueatlas                  |6.0.1-forge-mc1.16.5|CREATE_REG|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.2-server.jar                    |Minecraft                     |minecraft                     |1.16.5              |CREATE_REG|Manifest: NOSIGNATURE
		upgrade_aquatic-1.16.5-3.1.0.jar                  |Upgrade Aquatic               |upgrade_aquatic               |3.1.0               |CREATE_REG|Manifest: NOSIGNATURE
		endergetic-1.16.4-3.0.0.jar                       |The Endergetic Expansion      |endergetic                    |3.0.0               |CREATE_REG|Manifest: NOSIGNATURE
		swingthroughgrass-1.16.4-1.5.3.jar                |SwingThroughGrass             |swingthroughgrass             |1.16.4-1.5.3        |CREATE_REG|Manifest: NOSIGNATURE
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |CREATE_REG|Manifest: NOSIGNATURE
		Abundance-1.16.5-1.0.5.jar                        |Abundance                     |abundance                     |1.16.5-1.0.5        |CREATE_REG|Manifest: NOSIGNATURE
		Jade-1.16.4-2.7.2.jar                             |Jade                          |jade                          |2.7.2               |CREATE_REG|Manifest: NOSIGNATURE
		towers_of_the_wild-1.16.4-2.0.1.jar               |Towers Of The Wild            |towers_of_the_wild            |1.16.4-2.0.1        |CREATE_REG|Manifest: NOSIGNATURE
		lepton-1.16.5-1.3.1.jar                           |Lepton                        |lepton                        |1.3.1               |CREATE_REG|Manifest: NOSIGNATURE
		farmersdelightintegration-1.16.5-1.0.3.jar        |Farmer's Delight Integration  |farmersdelightintegration     |1.16.5-1.0.3        |CREATE_REG|Manifest: NOSIGNATURE
		personality-1.16.5-1.0.2.jar                      |Personality                   |personality                   |1.0.2               |CREATE_REG|Manifest: NOSIGNATURE
		atmospheric-1.16.5-3.1.0.jar                      |Atmospheric                   |atmospheric                   |3.1.0               |CREATE_REG|Manifest: NOSIGNATURE
		savageandravage-1.16.5-3.1.0.jar                  |Savage & Ravage               |savageandravage               |3.1.0               |CREATE_REG|Manifest: NOSIGNATURE
		Mantle-1.16.5-1.6.115.jar                         |Mantle                        |mantle                        |1.6.115             |CREATE_REG|Manifest: NOSIGNATURE
		Inspirations-1.16.5-1.2.3.38.jar                  |Inspirations                  |inspirations                  |1.2.3.38            |CREATE_REG|Manifest: NOSIGNATURE
		ftb-backups-2.1.1.6.jar                           |FTB Backups                   |ftbbackups                    |2.1.1.6             |CREATE_REG|Manifest: NOSIGNATURE
		autumnity-1.16.5-2.1.1.jar                        |Autumnity                     |autumnity                     |2.1.1               |CREATE_REG|Manifest: NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |CREATE_REG|Manifest: NOSIGNATURE
		Quark-r2.4-316.jar                                |Quark                         |quark                         |r2.4-316            |CREATE_REG|Manifest: NOSIGNATURE
		charm-forge-1.16.5-2.3.2.jar                      |Charm                         |charm                         |2.3.2               |CREATE_REG|Manifest: NOSIGNATURE
		charmonium-forge-1.16.5-2.3.2.jar                 |Charmonium                    |charmonium                    |2.3.2               |CREATE_REG|Manifest: NOSIGNATURE
		abnormals_delight-1.16.5-1.1.1.jar                |Abnormals Delight             |abnormals_delight             |1.1.1               |CREATE_REG|Manifest: NOSIGNATURE
		muchmoremodcompat-1.0.0.jar                       |Much More Mod Compat          |muchmoremodcompat             |NONE                |CREATE_REG|Manifest: NOSIGNATURE
		decorative_blocks-1.16.4-1.7.2.jar                |Decorative Blocks             |decorative_blocks             |1.7.2               |CREATE_REG|Manifest: NOSIGNATURE
		decorative_blocks_abnormals-1.2.jar               |Decorative Blocks Abnormals   |decorative_blocks_abnormals   |1.2                 |CREATE_REG|Manifest: NOSIGNATURE
		decorative_winter-0.1.2.jar                       |Decorative Winter             |decorative_winter             |0.1.2               |CREATE_REG|Manifest: NOSIGNATURE
		ScreenshotToClipboard-1.15.1-1.0.5.jar            |Screenshot to Clipboard       |screenshotclipboard           |1.15.1-1.0.5        |CREATE_REG|Manifest: NOSIGNATURE
		ferritecore-2.0.5-forge.jar                       |Ferrite Core                  |ferritecore                   |2.0.5               |CREATE_REG|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		step-1.16.4-1.1.0.jar                             |Step                          |step                          |1.1.0               |CREATE_REG|Manifest: NOSIGNATURE
		OpenLoader-1.16.5-9.0.3.jar                       |OpenLoader                    |openloader                    |9.0.3               |CREATE_REG|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		DefaultOptions_1.16.5-12.2.1.jar                  |Default Options               |defaultoptions                |12.2.1              |CREATE_REG|Manifest: NOSIGNATURE
	Crash Report UUID: cf35b41a-da62-454b-9ca2-e4820ee1a9a7
```

## Modpack Version
Crucial2-1.3.1-server

## Java Version
Both openjdk version "1.8.0_292" and openjdk version "11.0.11"

## Memory Allocated: 
-Xms2G -Xmx2G

**Comment by MatteoGisondi** [comment]
Duplicate #182, hotfix already issued.
